service: persistence-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI, 'mongodb://localhost:27017/wyd'}

plugins:
  - serverless-esbuild
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    autoCreate: true                 # create the queue automatically
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:4566    # LocalStack
    region: us-east-1
    accessKeyId: test
    secretAccessKey: test
    skipCacheInvalidation: false

functions:
  savePlayer:
    handler: handler.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GameEventsQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    GameEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: wyd-game-events
